services:
  - type: web
    name: whatsapp-webhook
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 3000
      - key: VERIFY_TOKEN
        sync: false
    autoDeploy: true